{% set name = "sphinx-autosummary-accessors" %}
{% set version = "2023.4.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 26f60f44dea2b4b487022921dfba6d773b4529b71afb7069cb97d4ceff0abab9

build:
  number: 0
  noarch: python
  script: SETUPTOOLS_SCM_PRETEND_VERSION={{ version }} {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
    - setuptools >=42
    - setuptools_scm >=3.4
    - toml
  run:
    - importlib-metadata
    - python >=3.7
    - sphinx >=3.3

test:
  imports:
    - sphinx_autosummary_accessors
  commands:
    - pip check
    - python -c 'from sphinx_autosummary_accessors import __version__; assert __version__ != "0.0.0"'
  requires:
    - pip

about:
  home: https://github.com/xarray-contrib/sphinx-autosummary-accessors
  summary: sphinx autosummary extension to properly format pandas or xarray accessors
  license: MIT
  license_file: LICENSE
  doc_url: https://sphinx-autosummary-accessors.readthedocs.io/
  dev_url: https://github.com/xarray-contrib/sphinx-autosummary-accessors

extra:
  recipe-maintainers:
    - conda-forge/sphinx
    - keewis
